title:
description:
images:
- cover.png

assets:
  remote:
    alpinejs:
      intersect: https://unpkg.com/@alpinejs/intersect@3.x.x/dist/cdn.min.js
      persist: https://unpkg.com/@alpinejs/persist@3.x.x/dist/cdn.min.js
      focus: https://unpkg.com/@alpinejs/focus@3.x.x/dist/cdn.min.js
      collapse: https://unpkg.com/@alpinejs/collapse@3.x.x/dist/cdn.min.js
      morph: https://unpkg.com/@alpinejs/morph@3.x.x/dist/cdn.min.js
      core: https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js
  src:
    css: app.css
    scss: app.scss
    js: app.js

googleFonts:
  notosanskr: https://fonts.googleapis.com/css2?family=Noto+Serif+KR:wght@400;700&display=swap
  notoserifkr: https://fonts.googleapis.com/css2?family=Noto+Serif+KR:wght@100;400;700&display=swap
