name = "Hugo tailpine"
license = "MIT"
licenselink = "https://github.com/mozodev/hugo-tailpine/blob/master/LICENSE"
description = ""
homepage = "https://hugo-tailpine.netlify.app"
tags = []
features = []
min_version = "0.91.2"

[author]
  name = "yeongtaek, Hong"
  homepage = "https://mozo.kr"
