name = "Hugo Talpine"
license = "MIT"
licenselink = "https://github.com/mozodev/hugo-talpine/blob/master/LICENSE"
description = ""
homepage = "https://hugo-talpine.netlify.app"
tags = []
features = []
min_version = "0.91.2"

[author]
  name = "yeongtaek, Hong"
  homepage = "https://mozo.kr"
