title: A website

baseURL: https://hugo-tailpine-dev.netlify.app
languageCode: ko-kr
defaultContentLanguage: ko
hasCJKLanguage: true

build:
  writeStats: true

outputFormats:
  og:
    baseName: og
    isHTML: true
    mediaType: text/html

outputs:
  page:
  - html
  - json
  - og
