title: A website

languageCode: ko-kr
defaultContentLanguage: ko
hasCJKLanguage: true

module:
  imports:
  - path: github.com/kaushalmodi/hugo-debugprint
  - path: github.com/mozodev/hugo-tailpine
  replacements: "github.com/mozodev/hugo-tailpine -> ../.."
