title: A website

languageCode: ko-kr
defaultContentLanguage: ko
hasCJKLanguage: true

module:
  imports:
  - path: github.com/kaushalmodi/hugo-debugprint
  - path: github.com/gohugoio/hugo-mod-heroicons
  - path: github.com/mozodev/hugo-tailpine

outputFormats:
  og:
    baseName: og
    isHTML: true
    mediaType: text/html

outputs:
  page:
  - html
  - json
  - og
