[functions]
  directory = "functions/"
  node_bundler = "esbuild"
  external_node_modules = ["google-spreadsheet"]

[dev]
  command = "yarn start"
  port = 8888
  targetPort = 1313
  publish = "public"
