[functions]
  node_bundler = "esbuild"
  external_node_modules = ["google-spreadsheet", "chrome-aws-lambda", "puppeteer-core"]

[[redirects]]
  from = "/og/*"
  to = "/.netlify/functions/og/:splat"

[dev]
  command = "yarn start"
  port = 8888
  targetPort = 1313
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
